project:
  type: website
  output-dir: docs

website:
  title: "Gavin Crooks"
  navbar:
    left:
      - href: index.qmd
        text: Home 
      - contact.qmd 
      - resume 
        
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

