project:
  type: website
  output-dir: docs

website:
  title: "Gavin Crooks"
  navbar:
    left:
      - href: index.qmd
        text: Home 
      - href: Contact.qmd 
        text: Contect me
      - href: Resume.qmd 
        text: Resume
        
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

